<?php if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_59fdaa304ca99',
	'title' => 'Member Information',
	'fields' => array (
		array (
			'key' => 'field_59fdaa37fce31',
			'label' => 'Profile',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fdaaf0fce32',
			'label' => 'First Name',
			'name' => 'first_name',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fdfa2d35703',
			'label' => 'Last Name',
			'name' => 'last_name',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0674e9c17',
			'label' => 'Gender',
			'name' => 'gender',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe069be9c18',
			'label' => 'Home Phone',
			'name' => 'home_phone',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '(xxx) xxx-xxxx',
			'prepend' => '',
			'append' => '',
			'maxlength' => 10,
		),
		array (
			'key' => 'field_59fe06ebe9c19',
			'label' => 'Cell Phone',
			'name' => 'cell_phone',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '(xxx) xxx-xxxx',
			'prepend' => '',
			'append' => '',
			'maxlength' => 10,
		),
		array (
			'key' => 'field_59fe0704e9c1a',
			'label' => 'Home Address',
			'name' => 'home_address',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '123 Fake St. Toronto, ON. M7M 7M7',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0759e9c1b',
			'label' => 'Email Address',
			'name' => 'email_address',
			'type' => 'email',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array (
			'key' => 'field_59fe07b9e9c1c',
			'label' => 'Birthday',
			'name' => 'birthday',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'December 1st, 1988',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe07f6e9c1d',
			'label' => 'Health Card Number',
			'name' => 'health_card_number',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0848e9c1e',
			'label' => 'Medical Conditions',
			'name' => 'medical_conditions',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_59fe086be9c1f',
			'label' => 'Current Medication',
			'name' => 'current_medication',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
		array (
			'key' => 'field_59fe08a8e9c21',
			'label' => 'Do They Have Allergies?',
			'name' => 'have_allergies',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59fe087ee9c20',
			'label' => 'Allergies',
			'name' => 'allergies',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59fe08a8e9c21',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'Add Allergy',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe0903e9c22',
					'label' => 'Allergy',
					'name' => 'allergy',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe0922e9c23',
					'label' => 'Emergency Plan',
					'name' => 'emergency_plan',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
			),
		),
		array (
			'key' => 'field_59fe0fcb10ce5',
			'label' => 'Do They Have Dietary Restrictions?',
			'name' => 'have_restrictions',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'yes' => 'Yes',
				'no' => 'No',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59fe09f5e9c25',
			'label' => 'Dietary Restrictions',
			'name' => 'dietary_restrictions',
			'type' => 'group',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59fe0fcb10ce5',
						'operator' => '==',
						'value' => 'yes',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe09aae9c24',
					'label' => 'Restrictions',
					'name' => 'restrictions',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'vegetarian' => 'Vegetarian',
						'vegan' => 'Vegan',
						'lactose intolerant' => 'Lactose Intolerant',
						'other' => 'Other',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59fe0a20e9c26',
					'label' => 'Other Restrictions',
					'name' => 'other_resctictions',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe09aae9c24',
								'operator' => '==',
								'value' => 'other',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_59fe1133b0678',
			'label' => 'Consent to Videos and Photography',
			'name' => 'consent_to_videos_and_photography',
			'type' => 'radio',
			'value' => NULL,
			'instructions' => 'I consent to the CEE Centre for Young Black Professionals {hereinafter referred to as CEE} and Eric Asante {herein after referred to as Videographer} its employees, agents, and partners to take photographs and digital recordings of me to develop the CEE Gala video series profiling award recipients who are creators and change makers in the community.	I further understand that the said media are used for profiling, promoting and marketing CEE affiliates, ambassadors and extended partners now and hereafter, privately or publicly. In so doing, your name and identity may be revealed by descriptive text or commentary. I waive any rights, claims, or interest to control the use of my identity or likeness in media used.	I understand that there will be no financial or other remuneration for recording me, either for initial or subsequent transmission or playback. I represent that I am at least 18 years of age, have read and understand the foregoing statement, and am competent to execute this agreement.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'no' => 'No',
				'yes' => 'Yes',
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => 'no',
			'layout' => 'vertical',
			'return_format' => 'value',
		),
		array (
			'key' => 'field_59fe0e9309c84',
			'label' => 'Contacts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe0ef009c89',
			'label' => 'Contact Information',
			'name' => 'contact_information',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe0ec209c85',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe0ec909c86',
					'label' => 'Relationship',
					'name' => 'relationship',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe0ed209c87',
					'label' => 'Phone Number',
					'name' => 'phone_number',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array (
			'key' => 'field_59fe13a8eacc8',
			'label' => 'Goals',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe1487eaccc',
			'label' => 'Goals',
			'name' => 'goals',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe14caeaccd',
					'label' => 'Date Recorded',
					'name' => 'date_recorded',
					'type' => 'date_picker',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_59fe14e7eacce',
					'label' => 'Recorded By',
					'name' => 'recorded_by',
					'type' => 'user',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_59fe13e3eacc9',
					'label' => 'What are you looking forward to accomplishing in the short-term (0 – 3 years)?',
					'name' => 'accomplishing_short-term',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_59fe1454eaccb',
					'label' => 'What motivates you and gives you that extra push to keep going?',
					'name' => 'what_motivates_you',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_59fe141beacca',
					'label' => 'Where do you want to see yourself in the short-term?',
					'name' => 'see_yourself',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_59fe169b24438',
					'label' => 'Considering your goals listed above, what do you think may make it challenging for you to achieve these (staff: briefly details the connection between goals and personal context)',
					'name' => 'challenges',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_59fe16d024439',
					'label' => 'Which areas were covered? (each selected item will produce a dropdown box for your notes)',
					'name' => 'which_areas_were_covered_each_selected_item_will_produce_a_dropdown_box_for_your_notes',
					'type' => 'group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59fe170e2443a',
							'label' => 'Family',
							'name' => 'family',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe17362443b',
							'label' => 'Family Cont\'d',
							'name' => 'family_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe170e2443a',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe177568f0e',
							'label' => 'Intimate Relationship',
							'name' => 'intimate_relationship',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe177f68f0f',
							'label' => 'Intimate Relationship Cont\'d',
							'name' => 'intimate_relationship_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe177568f0e',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe17be68f10',
							'label' => 'Housing',
							'name' => 'housing',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe17c268f11',
							'label' => 'Housing Cont\'d',
							'name' => 'housing_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe17be68f10',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe180568f12',
							'label' => 'Past Hurt',
							'name' => 'past_hurt',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe181368f13',
							'label' => 'Past Hurt Cont\'d',
							'name' => 'past_hurt_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe180568f12',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe184568f14',
							'label' => 'Safety',
							'name' => 'safety',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe184a68f15',
							'label' => 'Safety Cont\'d',
							'name' => 'safety_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe184568f14',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe18a018f75',
							'label' => 'Outstanding Legal Matter',
							'name' => 'outstanding_legal_matter',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe189e18f74',
							'label' => 'Outstanding Legal Matter Cont\'d',
							'name' => 'outstanding_legal_matter_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe18a018f75',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe19008e4b0',
							'label' => 'Mental Wellness',
							'name' => 'mental_wellness',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe18fe8e4af',
							'label' => 'Mental Wellness Cont\'d',
							'name' => 'mental_wellness_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe19008e4b0',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe19588e4b2',
							'label' => 'Recent Hurt',
							'name' => 'recent_hurt',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe19578e4b1',
							'label' => 'Recent Hurt Cont\'d',
							'name' => 'recent_hurt_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe19588e4b2',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe198c8e4b3',
							'label' => 'Physical Health',
							'name' => 'physical_health',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe198f8e4b4',
							'label' => 'Physical Health Cont\'d',
							'name' => 'physical_health_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe198c8e4b3',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array (
							'key' => 'field_59fe1a049a1ce',
							'label' => 'Financial/Monetary Challenges',
							'name' => 'financial_monetary_challeneges',
							'type' => 'radio',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'no' => 'No',
								'yes' => 'Yes',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'no',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array (
							'key' => 'field_59fe1a029a1cd',
							'label' => 'Financial/Monetary Challenges Cont\'d',
							'name' => 'financial_monetary_challeneges_contd',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array (
								array (
									array (
										'field' => 'field_59fe1a049a1ce',
										'operator' => '==',
										'value' => 'yes',
									),
								),
							),
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
			),
		),
		array (
			'key' => 'field_59fe1ecd09784',
			'label' => 'Background',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe1ef709785',
			'label' => 'Background',
			'name' => 'background',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add an Update',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe1f3009786',
					'label' => 'Date Recorded',
					'name' => 'date_recorded',
					'type' => 'date_picker',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_59fe1f6f09787',
					'label' => 'Recorded By',
					'name' => 'recorded_by',
					'type' => 'user',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => '',
					'allow_null' => 0,
					'multiple' => 0,
				),
				array (
					'key' => 'field_59fe1f9209788',
					'label' => 'Do you live in stable housing?',
					'name' => 'stable_housing',
					'type' => 'checkbox',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'yes' => 'Yes',
					),
					'allow_custom' => 0,
					'save_custom' => 0,
					'default_value' => array (
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe1fc609789',
					'label' => 'In general, how would you say your health is',
					'name' => 'your_health',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array (
					'key' => 'field_59fe20090978a',
					'label' => 'Do you have dependents?',
					'name' => 'dependents',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe20230978b',
					'label' => 'How many dependants?',
					'name' => 'how_many_dependants',
					'type' => 'number',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe20090978a',
								'operator' => '==',
								'value' => 'yes',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'min' => '',
					'max' => '',
					'step' => '',
				),
				array (
					'key' => 'field_59fe20500978c',
					'label' => 'Source of income?',
					'name' => 'source_of_income',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'-- Select --' => '-- Select --',
						'Family' => 'Family',
						'Temp Jobs' => 'Temp Jobs',
						'Part time work' => 'Part time work',
						'ODSP' => 'ODSP',
						'OW' => 'OW',
						'Full time work' => 'Full time work',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59fe20c70978d',
					'label' => 'Are you currently on probation or parole, or awaiting a hearing?',
					'name' => 'currently_on_probation',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => 'no : No
yes : Yes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe20e90978e',
					'label' => 'Within the last 5 years, have you been on probation or parole?',
					'name' => 'last_5_years_probation',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => 'no : No
yes : Yes',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe21060978f',
					'label' => 'What community do you live in?',
					'name' => 'what_community',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe211909790',
					'label' => 'Which ID do you have?',
					'name' => 'which_id',
					'type' => 'checkbox',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Driver license' => 'Driver license',
						'Ontario ID Card' => 'Ontario ID Card',
						'S.I.N Card' => 'S.I.N Card',
						'Health Card' => 'Health Card',
						'Passport' => 'Passport',
					),
					'allow_custom' => 0,
					'save_custom' => 0,
					'default_value' => array (
					),
					'layout' => 'vertical',
					'toggle' => 0,
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe215a09791',
					'label' => 'Emergency Contact',
					'name' => 'emergency_contact',
					'type' => 'group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59fe216709792',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59fe217109793',
							'label' => 'Relationship',
							'name' => 'relationship',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59fe217a09794',
							'label' => 'Phone',
							'name' => 'phone',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array (
					'key' => 'field_59fe219309795',
					'label' => 'Are you currently enrolled in school?',
					'name' => 'enrolled_in_school',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe21b209796',
					'label' => 'Are you currently employed?',
					'name' => 'currently_employed',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe21d709797',
					'label' => 'What was your last job?',
					'name' => 'last_job',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe21ea09798',
					'label' => 'Are you currently in an apprenticeship?',
					'name' => 'currently_apprenticeship',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe220709799',
					'label' => 'Any previous experience in a program?',
					'name' => 'previous_program',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe222f0979a',
					'label' => 'Program Name',
					'name' => 'program_name',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe220709799',
								'operator' => '==',
								'value' => 'yes',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe224b0979b',
					'label' => 'Program Status',
					'name' => 'program_status',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe220709799',
								'operator' => '==',
								'value' => 'yes',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe225a0979c',
					'label' => 'Have you completed the requirements for a high school diploma or its equivalent?',
					'name' => 'high_school_or_equivalent',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe22810979d',
					'label' => 'What is the highest grade level in high school you have completed?',
					'name' => 'highest_grade_level',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe225a0979c',
								'operator' => '==',
								'value' => 'no',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe22a40979e',
					'label' => 'What is the highest degree, certificate or diploma you have obtained',
					'name' => 'highest_degree',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe22ba0979f',
					'label' => 'Do you have a bank account?',
					'name' => 'bank_account',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_59fe22dd097a0',
					'label' => 'Do you use the bank account to save money, or have you saved in the past?',
					'name' => 'bank_account_to_save',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe22fe097a1',
					'label' => 'Do you have a goal for saving money?',
					'name' => 'goal_for_saving_money',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'no' => 'No',
						'yes' => 'Yes',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'no',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
			),
		),
		array (
			'key' => 'field_59fe37d912390',
			'label' => 'Programs',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe37e312391',
			'label' => 'Program',
			'name' => 'program',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe37ef12392',
					'label' => 'Name',
					'name' => 'name',
					'type' => 'post_object',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => array (
						0 => 'program_partner',
					),
					'taxonomy' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'return_format' => 'object',
					'ui' => 1,
				),
				array (
					'key' => 'field_59fe37f612393',
					'label' => 'Start Date',
					'name' => 'start_date',
					'type' => 'date_picker',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_59fe380312394',
					'label' => 'End Date',
					'name' => 'end_date',
					'type' => 'date_picker',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'center_lat' => '',
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_59fe380d12395',
					'label' => 'Status',
					'name' => 'status',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'current' => 'Currently Enrolled',
						'completed' => 'Completed',
					),
					'default_value' => array (
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_59fe39149c2e2',
					'label' => 'Notes',
					'name' => 'notes',
					'type' => 'repeater',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'sub_fields' => array (
						array (
							'key' => 'field_59fe39229c2e3',
							'label' => 'Date Taken',
							'name' => 'date_taken',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59fe395b9c2e4',
							'label' => 'Note',
							'name' => 'note',
							'type' => 'textarea',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
					),
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'cee_members',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

acf_add_local_field_group(array (
	'key' => 'group_59fe0d03bd193',
	'title' => 'Program Partner',
	'fields' => array (
		array (
			'key' => 'field_59fe0df7ea5cb',
			'label' => 'Program Contacts',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe0d1a86d9e',
			'label' => 'Program Name',
			'name' => 'program_name',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0d2f86d9f',
			'label' => 'Main Contact Person',
			'name' => 'main_contact_person',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0d6b86da0',
			'label' => 'Main Contact Person Email',
			'name' => 'main_contact_person_email',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe14702d736',
			'label' => 'Permissions',
			'name' => 'permissions',
			'type' => 'true_false',
			'value' => NULL,
			'instructions' => 'Would you like to grant this user permission to add comments to members enrolled in their program? (This will add them as a user to your website, but will not allow them to access the administration panel).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Grant Permission',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array (
			'key' => 'field_59fe17ca4db81',
			'label' => 'User',
			'name' => 'user',
			'type' => 'user',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array (
				array (
					array (
						'field' => 'field_59fe14702d736',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'role' => array (
				0 => 'subscriber',
			),
			'allow_null' => 0,
			'multiple' => 0,
		),
		array (
			'key' => 'field_59fe0d7586da1',
			'label' => 'Additional Program Contacts',
			'name' => 'additional_program_contacts',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe0d9586da2',
					'label' => 'Contact Name',
					'name' => 'contact_name',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe0da086da3',
					'label' => 'Contact Email',
					'name' => 'contact_email',
					'type' => 'text',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59fe14f62d737',
					'label' => 'Permissions',
					'name' => 'permissions_additional_',
					'type' => 'true_false',
					'value' => NULL,
					'instructions' => 'Would you like to grant this user permission to add comments to members enrolled in their program? (This will add them as a user to your website, but will not allow them to access the administration panel).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => 'Grant Permission',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array (
					'key' => 'field_59fe180bf0772',
					'label' => 'User_additional',
					'name' => 'user_copy',
					'type' => 'user',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59fe14702d736',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'role' => array (
						0 => 'subscriber',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
		),
		array (
			'key' => 'field_59fe0e381b110',
			'label' => 'Program Details',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe0e9c1b113',
			'label' => 'City',
			'name' => 'city',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0e771b111',
			'label' => 'Phone Number',
			'name' => 'phone_number',
			'type' => 'number',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array (
			'key' => 'field_59fe0e8c1b112',
			'label' => 'Address',
			'name' => 'address',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_59fe0ee61b114',
			'label' => 'Additional Program Information',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe0f091b115',
			'label' => 'Program Description',
			'name' => 'program_description',
			'type' => 'textarea',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 25,
			'new_lines' => '',
		),
		array (
			'key' => 'field_59fe0fd74ff09',
			'label' => 'Notes',
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array (
			'key' => 'field_59fe0f421b116',
			'label' => 'Program Notes',
			'name' => 'program_notes',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => 'Add notes about this partner.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59fe0f731b117',
					'label' => 'Date',
					'name' => 'date',
					'type' => 'date_picker',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '15',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'd/m/Y',
					'return_format' => 'd/m/Y',
					'first_day' => 1,
				),
				array (
					'key' => 'field_59fe0f9b1b118',
					'label' => 'Note',
					'name' => 'note',
					'type' => 'textarea',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 20,
					'new_lines' => '',
				),
			),
		),
		array (
			'key' => 'field_59fe15472d738',
			'label' => '',
			'name' => '',
			'type' => 'text',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'program_partner',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array (
		0 => 'permalink',
		1 => 'the_content',
		2 => 'excerpt',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'page_attributes',
		10 => 'featured_image',
		11 => 'categories',
		12 => 'tags',
		13 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;
